name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Add mongoDB as a service
    steps:
      - uses: actions/checkout@v3

      - name: Create dir
        run: mkdir TestArtifacts

      # Install Node on the runner
      - name: Node Installation
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Install dependencies
      - name: Dependency Installation
        run: npm install

      - name: "Setup .env file"
        run: echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env

      # Install Newman globally
      - name: Newman Installation
        run: |
          npm install -g newman
          npm install -g newman-reporter-slackreporter
          npm install -g newman-reporter-htmlextra

      - name: Start Server
        run: |
          npm run start &
          sleep 3

      - name: Run University Tests
        run: |
          cd src/PostmanCollection
          newman run "University.postman_collection.json" -e "workspace.postman_globals.json" -r cli,htmlextra --reporter-htmlextra-export ../../TestArtifacts/UniversityReport.html

      - name: Run Program Tests
        run: |
          cd src/PostmanCollection
          newman run "Program.postman_collection.json" -e "workspace.postman_globals.json" -r cli,htmlextra --reporter-htmlextra-export ../../TestArtifacts/ProgramReport.html

      - name: Run User Tests
        run: |
          cd src/PostmanCollection
          newman run "User.postman_collection.json" -e "workspace.postman_globals.json" -r cli,htmlextra --reporter-htmlextra-export ../../TestArtifacts/UserReport.html

      - name: Output Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: TestArtifacts
